// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SNCDatabase.DB;

#nullable disable

namespace SNCDatabase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250118173416_NewTable")]
    partial class NewTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SNCDatabase.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Ime")
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifra")
                        .HasColumnType("longtext");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Admini");
                });

            modelBuilder.Entity("SNCDatabase.Models.Dekorater", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("longtext");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOsnivanja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lokacija")
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .HasColumnType("longtext");

                    b.Property<float>("Ocena")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SigurnosniKod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Dekorateri");
                });

            modelBuilder.Entity("SNCDatabase.Models.Fotograf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("longtext");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("CenaPoSlici")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOsnivanja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lokacija")
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .HasColumnType("longtext");

                    b.Property<float>("Ocena")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SigurnosniKod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Fotografi");
                });

            modelBuilder.Entity("SNCDatabase.Models.Jelovnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImeJela")
                        .HasColumnType("longtext");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("RestoranID")
                        .HasColumnType("int");

                    b.Property<string>("TipJela")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Jelovnici");
                });

            modelBuilder.Entity("SNCDatabase.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<int>("DekoraterID")
                        .HasColumnType("int");

                    b.Property<int>("FotografID")
                        .HasColumnType("int");

                    b.Property<int>("MladenciID")
                        .HasColumnType("int");

                    b.Property<int>("PoslasticarID")
                        .HasColumnType("int");

                    b.Property<int>("RestoranID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("SNCDatabase.Models.MailCuvanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("MailCuvanje");
                });

            modelBuilder.Entity("SNCDatabase.Models.Mladenci", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Ime")
                        .HasColumnType("longtext");

                    b.Property<string>("ImePartneta")
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .HasColumnType("longtext");

                    b.Property<string>("PrezimePartnera")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Mladenci");
                });

            modelBuilder.Entity("SNCDatabase.Models.Poslasticar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("longtext");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOsnivanja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lokacija")
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .HasColumnType("longtext");

                    b.Property<float>("Ocena")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SigurnosniKod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Poslasticari");
                });

            modelBuilder.Entity("SNCDatabase.Models.Restoran", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("longtext");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOsnivanja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lokacija")
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .HasColumnType("longtext");

                    b.Property<float>("Ocena")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<bool>("PraviTortu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SigurnosniKod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Restorani");
                });

            modelBuilder.Entity("SNCDatabase.Models.SigurnosniKod", b =>
                {
                    b.Property<int>("SigKod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SigKod"));

                    b.HasKey("SigKod");

                    b.ToTable("SigurnosniKodovi");
                });

            modelBuilder.Entity("SNCDatabase.Models.SlobodanTermin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DekoraterID")
                        .HasColumnType("int");

                    b.Property<int>("FotografID")
                        .HasColumnType("int");

                    b.Property<int>("PoslasticarID")
                        .HasColumnType("int");

                    b.Property<int>("RestoranID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Termin")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("SlobodniTermini");
                });
#pragma warning restore 612, 618
        }
    }
}
